### ISSUE TITLE
Provide code in a zip file

### ISSUE THREAD

**Issue by clelange** [cms-opendata-workshop/workshop2022-lesson-cpp-root-python#10]
Given that the `Makefile`s need tabs, which aren't correctly reflected on the webpage when copying the code, and the code is quite lengthy, it would be good to provide the code in a zip file for download.

**Comment by mattbellis** [comment]
Done. Added to this lesson. 

https://cms-opendata-workshop.github.io/workshop2022-lesson-cpp-root-python/03-root-and-cpp-read-and-write/index.html
