### ISSUE TITLE
Consider using ROOT docker image instead of CMSSW one?

### ISSUE THREAD

**Issue by clelange** [cms-opendata-workshop/workshop2022-lesson-cpp-root-python#3]
Since these are largely pre-exercises, using a ROOT docker image would be easier (and it would also be clear that CMSSW isn't needed at all).

**Comment by mattbellis** [comment]
This is a fair point. Since this was designed to give participants some overview of how they would edit the C++ files (for example the POET lesson), I figured I would use the docker image we are using for the lessons to access the data. 

I was also trying to limit how many different docker images they need to work with. 

What are your thoughts about my motivation for sticking with the CMSSW image?

**Comment by katilp** [comment]
If the CMSSW docker is used, it should be the one for 2015 i.e. as in
https://cms-opendata-workshop.github.io/workshop2022-lesson-docker/03-docker-for-cms-opendata/index.html

However, now as I read, that points to cmsopendata/cmssw_7_6_7_vnc or cmsopendata/cmssw_7_6_7 while the portal docker page lists:

```
cmsopendata/cmssw_7_6_7-slc6_amd64_gcc493
gitlab-registry.cern.ch/cms-cloud/cmssw-docker-opendata/cmssw_7_6_7-slc6_amd64_gcc493
```

See https://github.com/cms-opendata-workshop/workshop2022-lesson-docker/issues/2

**Update**:

The docker image now updated to `cmssw_7_6_7-slc6_amd64_gcc493` in the docker pre-exercise. If it is decided to use the CMSSW container for this lesson as well, this is the image to be used.

**Comment by clelange** [comment]
The main motivation to switch would be that people could then also use `RDataFrame` and Python3.

**Comment by clelange** [comment]
Try the image provided at https://gitlab.cern.ch/cms-cloud/root-vnc (see README for how to use).

```
 docker run --rm -it -P -p 5901:5901 -p 6080:6080 gitlab-registry.cern.ch/cms-cloud/root-vnc:latest
```

The images don't contain editors (see #7)

**Comment by katilp** [comment]
[The docker tutorial](https://cms-opendata-workshop.github.io/workshop2022-lesson-docker/03-docker-for-cms-opendata/index.html) now has the instructions for the root container

**Comment by mattbellis** [comment]
Documentation now points to 7_6_7 for the C++/.C ROOT part of the lesson.

**Comment by mattbellis** [comment]
Oops. Sorry. Meant to edit to use the suggested ROOT and modern python container. Changing now.

**Comment by mattbellis** [comment]
OK, edits made to provide docker as options making use of the ROOT and python containers from the Docker pre-exercise.
