### ISSUE TITLE
Use a code formatter

### ISSUE THREAD

**Issue by clelange** [cms-opendata-workshop/workshop2022-lesson-cpp-root-python#4]
The style is a bit all over the place. If you run the code through a formatter, readability and consistency would increase.

**Comment by mattbellis** [comment]
Ouch! :) 

Do you mean for the C++ examples? Or just the explanatory text? I might be so blind to my poor formatting that I'm just not seeing it. :)

**Comment by clelange** [comment]
For the C++ examples - they already follow a certain style, but it might be easier to format the code using a program so that it's consistent (e.g. spaces)

**Comment by mattbellis** [comment]
I think this is OK now. Thanks for those edits.
