### ISSUE TITLE
Explain use of X forwarding

### ISSUE THREAD

**Issue by clelange** [cms-opendata-workshop/workshop2022-lesson-cpp-root-python#5]
https://cms-opendata-workshop.github.io/workshop2022-lesson-cpp-root-python/04-root-and-cpp-fill-a-histogram/index.html states that a "TBrowser window will pop up". Due to the way the container has been started in an earlier episode, this won't work.

**Comment by katilp** [comment]
If it is the CMSSW container and if it has been created as in https://cms-opendata-workshop.github.io/workshop2022-lesson-docker/03-docker-for-cms-opendata/index.html
the graphics will work in a similar way (either vnc or X-forwarding)

**Comment by mattbellis** [comment]
The lesson now says to use the ROOT container from the Docker pre-exercise and I *think* that exercise discusses how to handle graphics forwarding with either VNC or X-forwarding. 

I don't have a windows machine available and Sarah is home for the summer. But the docker pre-exercise should take care of this, right?

**Comment by katilp** [comment]
Yes, it will 👍

**Comment by mattbellis** [comment]
Huzzah!
