### ISSUE TITLE
Consider use of containers for "modern" python stack

### ISSUE THREAD

**Issue by clelange** [cms-opendata-workshop/workshop2022-lesson-cpp-root-python#6]
Local Python setups are hard to debug and I would personally expect a lot of people to fail.

For https://cms-opendata-workshop.github.io/workshop2022-lesson-cpp-root-python/06-set-up-local-python-environment/index.html, I'd suggest we also use a container image.

**Comment by mattbellis** [comment]
This is a fair comment and you might be right. We did discuss this as a meeting and decided we would try to run this tutorial with a local install, since we're just going to work with uproot and awkward. It also avoids any issues with X11 with on windows. 

However, if there are issues, we can always point them toward a standard docker image. Do you have a suggested image that has uproot/awkward and their dependencies? We can add the option to the lesson.

**Comment by katilp** [comment]
I'm also in favour of suggesting a container image, for the same reasons as Clemens. 
Ideally, it could have vnc installed as well in it if needed.

**Comment by smarkham11037** [comment]
Hi @clelange and @katilp . Dr. Bellis and I are working on this but neither of us have used docker to execute python scripts. Are recommending....

* Making use of a container image that puts us into an interactive mode in bash, and then executing the scripts that way? Or launching jupyter-notebooks from the container?

or

* Executing the script all at once with something like `docker run python OURSCRIPT.py`.

In either case, can you point us to an appropriate container and an example of how best to use it. We've been trying a few things but we just can seem to find the right combo. Thanks!

**Comment by smarkham11037** [comment]
Wait, maybe we might have something with...

```
docker run -v $HOME:$HOME -it  python /bin/bash 
```

stay tuned! :)

**Comment by smarkham11037** [comment]
Nevermind! We got something!

docker run -v $HOME:/root/ --net=host --env="DISPLAY" -v $HOME/.Xauthority:/root/.Xauthority:rw --name pytest  -it  python /bin/bash

**Comment by clelange** [comment]
I can help with the image, just let me know.

**Comment by smarkham11037** [comment]
Hi @clelange ! I am attempting to get this to work on a windows device and was curious if you have any advice. When running a script from inside docker no matplotlib plot images pop up. I'm running WSL2 and this is an issue even under 'regular' WSL2.

**Comment by clelange** [comment]
I'm working on a solution for this using VNC. I'll first have a ROOT container, then later a Python one. Can you let me know which Python packages you need to have installed in the Python one?

**Comment by smarkham11037** [comment]
@clelange It needs the numpy, matplotlib, uproot, awkward, and time packages. There's a chance the time package is already there (as in we didn't need to install it when running the docker command from an earlier comment) but I put in here just in case!

edit: It also needs the Jupyter package!

**Comment by clelange** [comment]
I've created an image at https://gitlab.cern.ch/cms-cloud/python-vnc (see README for how to use).

Run as follows:

```
 docker run --rm -it -P -p 5901:5901 -p 6080:6080 gitlab-registry.cern.ch/cms-cloud/python-vnc:latest
```

It doesn't contain Jupyter (yet). I can install it though, but then access would be different since one could simply start the Jupyter server in the container and connect to it from the host machine. There are a lot of images available that already do that.

For working with this image, start python in the terminal (and don't use the terminal in the VNC window since copy&paste is more difficult there). The matplotlib window will show up in the VNC window.

**Comment by clelange** [comment]
The images don't contain editors (see #7). Mount a local volume using the `-v` flag.

**Comment by katilp** [comment]
A very nice feature of this container is that it can read through xrootd and downloading files locally is not necessary. I've tested with one of the newly produced NanoAODRun1 files with a really lousy connection and the uproot/awkward example still goes very quickly. Remarkable!

That's with:
`infile_name = 'root://eospublic.cern.ch//eos/opendata/cms/upload/NanoAODRun1/01-Jul-22/Run2011B_DoubleMu/FC02A604-BC9A-4E26-A140-93D5A4044346.root'`

NB that the files will be moved under `/eos/opendata/cms/derived-data` where the other example files, such as the one used in this lesson, are readable with 

`infile_name = 'root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/ForHiggsTo4Leptons/SMHiggsToZZTo4L.root'`

**Comment by katilp** [comment]
Maybe xrootd is available with the root/uproot installation on the local computer as well. I do not know as I never bothered to install root locally. In that case, it would be best to instruct the option to read the file with the `root://eospublic.cern.ch//eos/opendata/cms/derived-data/` syntax in the instructions in all cases (whether local install or container).

**Comment by katilp** [comment]
[The docker tutorial](https://cms-opendata-workshop.github.io/workshop2022-lesson-docker/03-docker-for-cms-opendata/index.html) now has the instructions for the python container

**Comment by clelange** [comment]
> A very nice feature of this container is that it can read through xrootd and downloading files locally is not necessary. I've tested with one of the newly produced NanoAODRun1 files with a really lousy connection and the uproot/awkward example still goes very quickly. Remarkable!
> 
> That's with: `infile_name = 'root://eospublic.cern.ch//eos/opendata/cms/upload/NanoAODRun1/01-Jul-22/Run2011B_DoubleMu/FC02A604-BC9A-4E26-A140-93D5A4044346.root'`
> 
> NB that the files will be moved under `/eos/opendata/cms/derived-data` where the other example files, such as the one used in this lesson, are readable with
> 
> `infile_name = 'root://eospublic.cern.ch//eos/opendata/cms/derived-data/AOD2NanoAODOutreachTool/ForHiggsTo4Leptons/SMHiggsToZZTo4L.root'`

You find all the goodies 😄

**Comment by clelange** [comment]
@smarkham11037 The image now has Jupyter Lab and some instructions at https://gitlab.cern.ch/cms-cloud/python-vnc

**Comment by mattbellis** [comment]
OK, now using XrootD and the modern python container as an option.
