### ISSUE TITLE
Edit code outside container

### ISSUE THREAD

**Issue by clelange** [cms-opendata-workshop/workshop2022-lesson-cpp-root-python#7]
There is in principle no reason why participants have to edit their code using `nano` or `vi` in the container. Instead, they could mount a working directory when starting a container and edit their files with an editor that they have installed on their computer.

**Comment by clelange** [comment]
Recommendation is to mount to `/code` in the container since the `$HOME` dir should not be overwritten.

**Comment by mattbellis** [comment]
Added language to lesson to emphasize use of local editors.
