### ISSUE TITLE
No cmsenv in the CMSSW containers

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2022-lesson-cpp-root-python#9]
In https://cms-opendata-workshop.github.io/workshop2022-lesson-cpp-root-python/02-cpp-hello-world/index.html:

If we stick to CMSSW containers, note that `cmsenv` should **not** be done in them. It will unset some updated environment variables and make `curl` and `git clone` fail

**Comment by mattbellis** [comment]
No longer using CMSSW containers for this lesson.
